# Generated by Django 4.0.5 on 2022-06-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butce', '0002_cuzdan_delete_bakiye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuzdan',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='cuzdan',
            name='slug',
        ),
        migrations.AddField(
            model_name='cuzdan',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuzdan',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
