# Generated by Django 4.0.5 on 2022-06-20 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('butce', '0003_remove_cuzdan_budget_remove_cuzdan_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuzdan',
            old_name='amount',
            new_name='budget',
        ),
        migrations.AlterField(
            model_name='cuzdan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cuzdan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butce.cuzdan')),
            ],
        ),
    ]
