# Generated by Django 4.0.5 on 2022-06-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butce', '0005_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('balance', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='cuzdan',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Cuzdan',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
