# Generated by Django 4.0.5 on 2022-06-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butce', '0006_transaction_wallet_remove_expense_cuzdan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(max_length=5),
        ),
    ]
