# Generated by Django 4.0.5 on 2022-06-26 12:58

import butce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butce', '0008_category_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=150, null=True, verbose_name=butce.models.Category),
        ),
    ]
